<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // ===== MAKANAN & MINUMAN =====
            [
                'category_id' => 6,
                'name' => 'Good Day Cappuccino',
                'description' => 'Kopi kapucino instant dengan rasa creamy, aroma kopi yang gurih dan nikmat',
                'price_unit' => 8000,
                'price_bulk_4' => 7500,
                'price_dozen' => 80000,
                'stock' => 150,
                'min_stock' => 30,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/gooddaycapuchino.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Milo Bubuk Cokelat',
                'description' => 'Milo bubuk cokelat premium, kaya nutrisi dan energi untuk keluarga Indonesia',
                'price_unit' => 25000,
                'price_bulk_4' => 23000,
                'price_dozen' => 250000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/milobubuk.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pocari Sweat 500ml',
                'description' => 'Minuman isotonik Pocari Sweat, menyegarkan dan mengembalikan cairan tubuh',
                'price_unit' => 8000,
                'price_bulk_4' => 7500,
                'price_dozen' => 80000,
                'stock' => 200,
                'min_stock' => 40,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/pocarysweet.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Susu Kental Manis Bingkisan',
                'description' => 'Susu kental manis dalam kemasan bingkisan, cocok untuk hadiah dan penggunaan pribadi',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 120,
                'min_stock' => 25,
                'unit' => 'Pcs',
                'box_item_count' => 15,
                'image' => 'products/susukentalbingkisan.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Susu Kental Manis Kaleng',
                'description' => 'Susu kental manis premium dalam kemasan kaleng, tahan lama dan higienis',
                'price_unit' => 15000,
                'price_bulk_4' => 13500,
                'price_dozen' => 150000,
                'stock' => 180,
                'min_stock' => 36,
                'unit' => 'Pcs',
                'box_item_count' => 24,
                'image' => 'products/susukentalkaleng.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Neo Coffee',
                'description' => 'Kopi premium Neo dengan rasa yang kuat dan nikmat, sempurna untuk dinikmati kapan saja',
                'price_unit' => 5000,
                'price_bulk_4' => 4500,
                'price_dozen' => 50000,
                'stock' => 250,
                'min_stock' => 50,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/neocopi.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Sariwangi Teh Hijau',
                'description' => 'Teh hijau Sariwangi dengan aroma segar dan manfaat kesehatan yang luar biasa',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 25,
                'image' => 'products/sariwangiteh2.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Indomie Sedap Goreng',
                'description' => 'Mie goreng sedap dengan rasa gurih dan bumbu yang pas, favorit keluarga Indonesia',
                'price_unit' => 2500,
                'price_bulk_4' => 2300,
                'price_dozen' => 25000,
                'stock' => 500,
                'min_stock' => 100,
                'unit' => 'Pcs',
                'box_item_count' => 20,
                'image' => 'products/miesedap.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Mie Sari Rasa Ayam',
                'description' => 'Mie sari dengan cita rasa ayam yang lezat, lembut dan mudah dimasak',
                'price_unit' => 2500,
                'price_bulk_4' => 2300,
                'price_dozen' => 25000,
                'stock' => 400,
                'min_stock' => 80,
                'unit' => 'Pcs',
                'box_item_count' => 20,
                'image' => 'products/miesari.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Mie China Telur',
                'description' => 'Mie kuning dari China dengan tekstur yang kenyal dan cita rasa autentik',
                'price_unit' => 3000,
                'price_bulk_4' => 2700,
                'price_dozen' => 30000,
                'stock' => 300,
                'min_stock' => 60,
                'unit' => 'Pcs',
                'box_item_count' => 15,
                'image' => 'products/miechina.png',
            ],

            // ===== BUMBU & SAUS (Kategori 3) =====
            [
                'category_id' => 3,
                'name' => 'Kecap Manis ABC',
                'description' => 'Kecap manis ABC dengan rasa yang mantap dan warna yang dalam, pilihan utama untuk masakan',
                'price_unit' => 18000,
                'price_bulk_4' => 16500,
                'price_dozen' => 180000,
                'stock' => 120,
                'min_stock' => 25,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/sambaabc.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Kecap Manis Biasa',
                'description' => 'Kecap manis tradisional dengan rasa yang gurih dan cocok untuk segala hidangan',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 140,
                'min_stock' => 28,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/kecapmanis.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Kecap Murni Original',
                'description' => 'Kecap murni asli dengan bahan pilihan, murni tanpa pengawet berbahaya',
                'price_unit' => 15000,
                'price_bulk_4' => 13500,
                'price_dozen' => 150000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/kecapmurni.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Kecap China',
                'description' => 'Kecap China dengan rasa yang kuat dan unik, cocok untuk masakan Cina',
                'price_unit' => 20000,
                'price_bulk_4' => 18000,
                'price_dozen' => 200000,
                'stock' => 80,
                'min_stock' => 16,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/kecapcina.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Royco Bumbu Ayam',
                'description' => 'Royco bumbu ayam instant, lengkap dengan cita rasa dan mudah digunakan',
                'price_unit' => 4000,
                'price_bulk_4' => 3500,
                'price_dozen' => 40000,
                'stock' => 200,
                'min_stock' => 40,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/roycoayam.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Royco Bumbu Jagung',
                'description' => 'Royco bumbu jagung manis dengan aroma yang lezat dan nikmat',
                'price_unit' => 4000,
                'price_bulk_4' => 3500,
                'price_dozen' => 40000,
                'stock' => 180,
                'min_stock' => 36,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/roycojagung.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Mustard Sauce',
                'description' => 'Saus mustard lezat dengan rasa yang tajam dan sempurna untuk hidangan favorit',
                'price_unit' => 8000,
                'price_bulk_4' => 7200,
                'price_dozen' => 80000,
                'stock' => 90,
                'min_stock' => 18,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/mustard.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Minyak Goreng Premium',
                'description' => 'Minyak goreng berkualitas premium dengan hasil gorengan yang renyah dan gurih',
                'price_unit' => 35000,
                'price_bulk_4' => 32000,
                'price_dozen' => 350000,
                'stock' => 120,
                'min_stock' => 25,
                'unit' => 'Pcs',
                'box_item_count' => 5,
                'image' => 'products/minyakgoreng.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Minyak Oles Urut',
                'description' => 'Minyak urut tradisional dengan bahan herbal yang hangat dan nyaman di kulit',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/minyakurut.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Minyak Kelapa Resep',
                'description' => 'Minyak kelapa dengan resep tradisional, wangi dan bagus untuk kepala',
                'price_unit' => 25000,
                'price_bulk_4' => 22000,
                'price_dozen' => 250000,
                'stock' => 80,
                'min_stock' => 16,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/minyakres.png',
            ],
            [
                'category_id' => 3,
                'name' => 'Kimchi Asli Korea',
                'description' => 'Kimchi asli Korea dengan rasa pedas dan gurih yang autentik, kaya probiotik',
                'price_unit' => 30000,
                'price_bulk_4' => 27000,
                'price_dozen' => 300000,
                'stock' => 60,
                'min_stock' => 12,
                'unit' => 'Pcs',
                'box_item_count' => 4,
                'image' => 'products/kimchi.png',
            ],

            // ===== PRODUK KEBERSIHAN & KESEHATAN =====
            [
                'category_id' => 6,
                'name' => 'Dove Sabun Wajah',
                'description' => 'Sabun wajah Dove dengan formula lembut, menjaga kelembaban alami kulit',
                'price_unit' => 22000,
                'price_bulk_4' => 20000,
                'price_dozen' => 220000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/dove.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pepsodent Pasta Gigi',
                'description' => 'Pasta gigi Pepsodent dengan fluoride, menjaga gigi putih dan sehat',
                'price_unit' => 16000,
                'price_bulk_4' => 14500,
                'price_dozen' => 160000,
                'stock' => 150,
                'min_stock' => 30,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/pepsodent.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Sikat Gigi Berkualitas',
                'description' => 'Sikat gigi dengan bulu lembut dan gagang ergonomis, nyaman digunakan',
                'price_unit' => 8000,
                'price_bulk_4' => 7200,
                'price_dozen' => 80000,
                'stock' => 200,
                'min_stock' => 40,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/sikatgigi.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Listerine Mouthwash',
                'description' => 'Obat kumur Listerine, membunuh bakteri dan memberikan napas segar sepanjang hari',
                'price_unit' => 35000,
                'price_bulk_4' => 32000,
                'price_dozen' => 350000,
                'stock' => 80,
                'min_stock' => 16,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/listreine.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Shampoo Clear Anti Ketombe',
                'description' => 'Shampo Clear dengan formula anti ketombe, rambut sehat dan berkilau',
                'price_unit' => 28000,
                'price_bulk_4' => 25000,
                'price_dozen' => 280000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/clearshampoo2.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Biore UV Sunscreen',
                'description' => 'Sunscreen Biore UV dengan SPF tinggi, melindungi kulit dari sinar matahari',
                'price_unit' => 45000,
                'price_bulk_4' => 40000,
                'price_dozen' => 450000,
                'stock' => 60,
                'min_stock' => 12,
                'unit' => 'Pcs',
                'box_item_count' => 4,
                'image' => 'products/bioreUV.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Biore Men Skincare',
                'description' => 'Skincare khusus pria Biore, menjaga kulit tetap sehat dan segar',
                'price_unit' => 50000,
                'price_bulk_4' => 45000,
                'price_dozen' => 500000,
                'stock' => 50,
                'min_stock' => 10,
                'unit' => 'Pcs',
                'box_item_count' => 4,
                'image' => 'products/menbiore.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Nivea Men Cream',
                'description' => 'Krim wajah Nivea untuk pria, melembabkan dan menjaga kulit tetap muda',
                'price_unit' => 48000,
                'price_bulk_4' => 43000,
                'price_dozen' => 480000,
                'stock' => 55,
                'min_stock' => 11,
                'unit' => 'Pcs',
                'box_item_count' => 4,
                'image' => 'products/niveamen2.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Nivea Men Grooming Pack',
                'description' => 'Paket grooming pria Nivea lengkap dengan berbagai produk perawatan',
                'price_unit' => 55000,
                'price_bulk_4' => 50000,
                'price_dozen' => 550000,
                'stock' => 40,
                'min_stock' => 8,
                'unit' => 'Pcs',
                'box_item_count' => 3,
                'image' => 'products/niveamenpack2.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pond\'s Night Cream',
                'description' => 'Krim malam Pond\'s untuk perawatan intensif kulit wajah',
                'price_unit' => 45000,
                'price_bulk_4' => 40000,
                'price_dozen' => 450000,
                'stock' => 70,
                'min_stock' => 14,
                'unit' => 'Pcs',
                'box_item_count' => 5,
                'image' => 'products/ponds.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pond\'s Men Day Cream',
                'description' => 'Krim siang khusus pria Pond\'s, melindungi dan menjaga kesehatan kulit',
                'price_unit' => 42000,
                'price_bulk_4' => 38000,
                'price_dozen' => 420000,
                'stock' => 65,
                'min_stock' => 13,
                'unit' => 'Pcs',
                'box_item_count' => 5,
                'image' => 'products/ponst1.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pond\'s Men Twin Pack',
                'description' => 'Paket dua produk perawatan pria dari Pond\'s, lengkap dan ekonomis',
                'price_unit' => 75000,
                'price_bulk_4' => 68000,
                'price_dozen' => 750000,
                'stock' => 50,
                'min_stock' => 10,
                'unit' => 'Pcs',
                'box_item_count' => 3,
                'image' => 'products/poundtwind.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pound Men Pack',
                'description' => 'Paket lengkap produk perawatan pria dengan kualitas premium',
                'price_unit' => 72000,
                'price_bulk_4' => 65000,
                'price_dozen' => 720000,
                'stock' => 55,
                'min_stock' => 11,
                'unit' => 'Pcs',
                'box_item_count' => 3,
                'image' => 'products/poundmen.png',
            ],

            // ===== OBAT & KESEHATAN =====
            [
                'category_id' => 6,
                'name' => 'Tolak Angin Herbal',
                'description' => 'Obat herbal Tolak Angin, mengatasi gejala masuk angin secara alami',
                'price_unit' => 18000,
                'price_bulk_4' => 16000,
                'price_dozen' => 180000,
                'stock' => 130,
                'min_stock' => 26,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/tolakangin.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Salonpas Koyo',
                'description' => 'Koyo Salonpas untuk nyeri otot, panas dan mudah digunakan',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/salonpas.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Obat Herbal Tradisional',
                'description' => 'Obat herbal tradisional dengan bahan alami untuk berbagai keluhan kesehatan',
                'price_unit' => 25000,
                'price_bulk_4' => 22000,
                'price_dozen' => 250000,
                'stock' => 80,
                'min_stock' => 16,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/obat.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Total Obat Jamur Kaki',
                'description' => 'Obat khusus untuk mengatasi jamur kaki dengan efektif dan aman',
                'price_unit' => 35000,
                'price_bulk_4' => 31000,
                'price_dozen' => 350000,
                'stock' => 60,
                'min_stock' => 12,
                'unit' => 'Pcs',
                'box_item_count' => 5,
                'image' => 'products/totolekaldujamur.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Hit Nyamuk Spray',
                'description' => 'Spray nyamuk Hit yang efektif membunuh nyamuk dan serangga lainnya',
                'price_unit' => 28000,
                'price_bulk_4' => 25000,
                'price_dozen' => 280000,
                'stock' => 110,
                'min_stock' => 22,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/hitnyamuk.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Vape Nyamuk Elektrik',
                'description' => 'Alat vape nyamuk elektrik dengan tekhnologi modern, aman untuk keluarga',
                'price_unit' => 45000,
                'price_bulk_4' => 40000,
                'price_dozen' => 450000,
                'stock' => 50,
                'min_stock' => 10,
                'unit' => 'Pcs',
                'box_item_count' => 4,
                'image' => 'products/vapenyamuk.png',
            ],

            // ===== PRODUK RUMAH TANGGA =====
            [
                'category_id' => 6,
                'name' => 'Detergen Cair Omo',
                'description' => 'Detergen cair dengan formula yang kuat membersihkan noda membandel',
                'price_unit' => 30000,
                'price_bulk_4' => 27000,
                'price_dozen' => 300000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/detergencair.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Mama Cabe Pembersih Piring',
                'description' => 'Pembersih piring Mama Cabe yang efektif menghilangkan minyak dan noda',
                'price_unit' => 8000,
                'price_bulk_4' => 7200,
                'price_dozen' => 80000,
                'stock' => 180,
                'min_stock' => 36,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/mamacucipiring.png',
            ],
            [
                'category_id' => 6,
                'name' => 'So Soft Detergen Pakaian',
                'description' => 'Detergen pakaian So Soft dengan aroma segar yang tahan lama',
                'price_unit' => 28000,
                'price_bulk_4' => 25000,
                'price_dozen' => 280000,
                'stock' => 95,
                'min_stock' => 19,
                'unit' => 'Pcs',
                'box_item_count' => 7,
                'image' => 'products/sosoftdetergen.png',
            ],

            // ===== MAKANAN RINGAN & COKELAT =====
            [
                'category_id' => 6,
                'name' => 'Excelso Kopi Premium',
                'description' => 'Kopi premium Excelso dengan biji kopi pilihan dan rasa yang istimewa',
                'price_unit' => 55000,
                'price_bulk_4' => 50000,
                'price_dozen' => 550000,
                'stock' => 70,
                'min_stock' => 14,
                'unit' => 'Pcs',
                'box_item_count' => 5,
                'image' => 'products/excelso.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Silver Queen Cokelat',
                'description' => 'Cokelat Silver Queen dengan rasa yang lezat dan kualitas terjamin',
                'price_unit' => 22000,
                'price_bulk_4' => 20000,
                'price_dozen' => 220000,
                'stock' => 150,
                'min_stock' => 30,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/silverqueen.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Walter Chocolate Cokelat Susu',
                'description' => 'Cokelat susu Walter yang lembut dan nikmat di mulut',
                'price_unit' => 18000,
                'price_bulk_4' => 16000,
                'price_dozen' => 180000,
                'stock' => 130,
                'min_stock' => 26,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/waltercholact.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Biskit Renyah Almond',
                'description' => 'Biskit renyah dengan almond pilihan, cocok untuk camilan keluarga',
                'price_unit' => 32000,
                'price_bulk_4' => 29000,
                'price_dozen' => 320000,
                'stock' => 80,
                'min_stock' => 16,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/biskuit.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Classic Waffer Premium',
                'description' => 'Waffer premium dengan rasa yang lezat dan tekstur yang renyah',
                'price_unit' => 28000,
                'price_bulk_4' => 25000,
                'price_dozen' => 280000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/classicwaffer.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Twister Biscuit Lezat',
                'description' => 'Biscuit twisted Twister dengan rasa keju yang kuat dan gurih',
                'price_unit' => 22000,
                'price_bulk_4' => 20000,
                'price_dozen' => 220000,
                'stock' => 120,
                'min_stock' => 24,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/twister.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Tessa Tissue Gulung',
                'description' => 'Tissue gulung Tessa yang lembut dan tebal, nyaman untuk keluarga',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 200,
                'min_stock' => 40,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/tessa.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Tessa Tissue Kotak',
                'description' => 'Tissue kotak Tessa premium, elegan dan praktis untuk meja',
                'price_unit' => 15000,
                'price_bulk_4' => 13500,
                'price_dozen' => 150000,
                'stock' => 180,
                'min_stock' => 36,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/tessatisu.png',
            ],

            // ===== MAKANAN & MINUMAN LAINNYA =====
            [
                'category_id' => 6,
                'name' => 'Sunlight Pink Dishwashing',
                'description' => 'Sunlight Pink pembersih piring yang wangi dan efektif membersihkan',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 140,
                'min_stock' => 28,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/sunlichpink.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Sunlight Dishwashing',
                'description' => 'Sunlight pembersih piring original dengan formula yang kuat',
                'price_unit' => 10000,
                'price_bulk_4' => 9200,
                'price_dozen' => 100000,
                'stock' => 160,
                'min_stock' => 32,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/sunlight.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Mama Jeruk Fresh',
                'description' => 'Minuman segar dari Mama Jeruk dengan rasa jeruk yang alami',
                'price_unit' => 5000,
                'price_bulk_4' => 4500,
                'price_dozen' => 50000,
                'stock' => 250,
                'min_stock' => 50,
                'unit' => 'Pcs',
                'box_item_count' => 15,
                'image' => 'products/mamajeruk.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Sedap Cup Noodles',
                'description' => 'Mie sedap dalam cup yang praktis dan cepat dimasak',
                'price_unit' => 3500,
                'price_bulk_4' => 3200,
                'price_dozen' => 35000,
                'stock' => 300,
                'min_stock' => 60,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/sedapcup.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Sedap Panas Spicy',
                'description' => 'Mie Sedap dengan rasa panas dan pedas yang menggugah selera',
                'price_unit' => 2500,
                'price_bulk_4' => 2300,
                'price_dozen' => 25000,
                'stock' => 400,
                'min_stock' => 80,
                'unit' => 'Pcs',
                'box_item_count' => 20,
                'image' => 'products/sedappanasspiccy.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Lasagna Pasta Italia',
                'description' => 'Lasagna pasta import dari Italia dengan tekstur yang pas',
                'price_unit' => 45000,
                'price_bulk_4' => 40000,
                'price_dozen' => 450000,
                'stock' => 50,
                'min_stock' => 10,
                'unit' => 'Pcs',
                'box_item_count' => 4,
                'image' => 'products/lasagna.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Oval Indomie Kecil',
                'description' => 'Oval indomie ukuran kecil untuk camilan praktis',
                'price_unit' => 2000,
                'price_bulk_4' => 1800,
                'price_dozen' => 20000,
                'stock' => 500,
                'min_stock' => 100,
                'unit' => 'Pcs',
                'box_item_count' => 25,
                'image' => 'products/ovalincekecil.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Oval Indomie Original',
                'description' => 'Oval Indomie original dengan rasa yang gurih dan nikmat',
                'price_unit' => 2500,
                'price_bulk_4' => 2300,
                'price_dozen' => 25000,
                'stock' => 450,
                'min_stock' => 90,
                'unit' => 'Pcs',
                'box_item_count' => 20,
                'image' => 'products/ovaline.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Chacha Sereal Manis',
                'description' => 'Sereal Chacha dengan rasa manis dan crunchy, cocok untuk sarapan',
                'price_unit' => 35000,
                'price_bulk_4' => 31000,
                'price_dozen' => 350000,
                'stock' => 70,
                'min_stock' => 14,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/chacha.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Cipta Dent Pasta Gigi',
                'description' => 'Pasta gigi Cipta Dent dengan rasa mint yang segar',
                'price_unit' => 14000,
                'price_bulk_4' => 12500,
                'price_dozen' => 140000,
                'stock' => 160,
                'min_stock' => 32,
                'unit' => 'Pcs',
                'box_item_count' => 12,
                'image' => 'products/ciptadent.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Citra Lotion Kulit',
                'description' => 'Lotion Citra dengan formula lembut untuk kulit yang halus dan lembab',
                'price_unit' => 32000,
                'price_bulk_4' => 29000,
                'price_dozen' => 320000,
                'stock' => 85,
                'min_stock' => 17,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/citra.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Bango Kecap Biasa',
                'description' => 'Kecap Bango dengan rasa yang mantap dan cocok untuk segala hidangan',
                'price_unit' => 12000,
                'price_bulk_4' => 11000,
                'price_dozen' => 120000,
                'stock' => 150,
                'min_stock' => 30,
                'unit' => 'Pcs',
                'box_item_count' => 10,
                'image' => 'products/bango.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Kapa Napi Pakaian Dalam',
                'description' => 'Pakaian dalam Kapa Napi dengan kualitas nyaman dan tahan lama',
                'price_unit' => 65000,
                'price_bulk_4' => 58000,
                'price_dozen' => 650000,
                'stock' => 40,
                'min_stock' => 8,
                'unit' => 'Pcs',
                'box_item_count' => 3,
                'image' => 'products/kapanapi.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Kapa Lapi Pack Isi 3',
                'description' => 'Paket isi 3 pakaian dalam Kapa Lapi berkualitas premium',
                'price_unit' => 180000,
                'price_bulk_4' => 162000,
                'price_dozen' => 1800000,
                'stock' => 30,
                'min_stock' => 6,
                'unit' => 'Pcs',
                'box_item_count' => 2,
                'image' => 'products/kapalapipack.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pepsodent 2 Tube Pack',
                'description' => 'Paket dua tube pasta gigi Pepsodent dengan harga lebih ekonomis',
                'price_unit' => 28000,
                'price_bulk_4' => 25000,
                'price_dozen' => 280000,
                'stock' => 120,
                'min_stock' => 24,
                'unit' => 'Pcs',
                'box_item_count' => 8,
                'image' => 'products/pepsodent2.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Pepsodent Bracket Pack',
                'description' => 'Pepsodent khusus untuk pengguna kawat gigi dalam paket hemat',
                'price_unit' => 32000,
                'price_bulk_4' => 29000,
                'price_dozen' => 320000,
                'stock' => 100,
                'min_stock' => 20,
                'unit' => 'Pcs',
                'box_item_count' => 6,
                'image' => 'products/pepsodent (2).png',
            ],
            [
                'category_id' => 6,
                'name' => 'Natural Produk Organik',
                'description' => 'Produk alami dan organik yang aman untuk seluruh keluarga',
                'price_unit' => 55000,
                'price_bulk_4' => 50000,
                'price_dozen' => 550000,
                'stock' => 45,
                'min_stock' => 9,
                'unit' => 'Pcs',
                'box_item_count' => 4,
                'image' => 'products/natural.png',
            ],
            [
                'category_id' => 6,
                'name' => 'Vector Logo Design',
                'description' => 'Produk dengan desain vector modern dan menarik',
                'price_unit' => 75000,
                'price_bulk_4' => 68000,
                'price_dozen' => 750000,
                'stock' => 35,
                'min_stock' => 7,
                'unit' => 'Pcs',
                'box_item_count' => 2,
                'image' => 'products/vector.png',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}

